# Using 4.1.0 explicitly because as of 6/15, 4.1.1 did not have required certs installed
FROM clearlinux/tesseract-ocr:4.1.0

# Set the working directory to /app
WORKDIR /app

RUN swupd bundle-add curl
RUN swupd bundle-add opencv-python
RUN swupd bundle-add devpkg-leptonica

ADD requirements.txt /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt


